
name: Node Test
on: workflow_dispatch
jobs:
  setup-node:
    runs-on: [ubuntu-latest]
    container: 
      image: centos:7
    steps:
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'
      - uses: actions/checkout@v2
      - run: cat README.md
    
